export enum ActionType {
  ADD_NEW_PRODUCT_START = 'ADD_NEW_PRODUCT_START',
  FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START',
  SET_MULTIPLE_PRODUCTS = 'SET_MULTIPLE_PRODUCTS',
  SET_PRODUCT = 'SET_PRODUCT',
  DELETE_PRODUCT_START = 'DELETE_PRODUCT_START',
}
